apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ncnt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-ncnt@sha256:34b53523041de24f41ec77e34d0024db7b8365e2be2632c4c005e357f42e5e3c
        name: my-nodejs
        resources: {}
status: {}
